title: "AURORA app"
email: auroraforwomen@gmail.com
timezone: UTC
baseurl: "/AURORA-app"
permalink: "/:title/"
logo: 'assets/images/hitgirl_aurora.png'
favicon: 'assets/images/aurora_ic.ico'
author: AURORA app
paginate: 30
disqus: 'AURORAapp'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: AURORA app
    display_name: AURORA app
    avatar: 'assets/images/sal.png'
    email: auroraforwomen@gmail.com
    web: auroraapp.github.io
    twitter: https://twitter.com/Aurora_app_
    description: "El equipo de AURORA app te ha traido esta publicación con mucho amor, siguenos en TikTok, Instagram, Twitter, Youtube y descarga AURORA app en iOS y Android para que este proyecto continúe."
  AURORA app:
    name: AURORA app
    display_name: AURORA app
    avatar: 'https://pbs.twimg.com/profile_images/1622016608196501504/dVSjugEK_400x400.jpg'
    email: auroraforwomen@gmail.com
    web: auroraapp.github.io
    twitter: https://twitter.com/Aurora_app_
    description: "El equipo de AURORA app te ha traido esta publicación con mucho amor, siguenos en TikTok, Instagram, Twitter, Youtube, Facebook y descarga AURORA app en iOS y Android para que este proyecto continúe."

# Social
social:
  instagram: https://www.instagram.com/aurora_app_/
  facebook: https://www.facebook.com/profile.php?id=100090112058218
  twitter: https://twitter.com/Aurora_app_

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives